### ISSUE TITLE
[Bug] Query function have to specific vector field in queryRequest

### ISSUE THREAD

**Issue by Penggeor** [pinecone-io/pinecone-ts-client#49]
### Is this a new bug?

- [X] I believe this is a new bug
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

I want query all vector: 
```ts
const target = await pineconeIndex.query({
  queryRequest: {
    topK: 10000,
    includeMetadata: true,
    includeValues: true,
    namespace: '',
  },
})
```
This is valid for typescript check but will throw an error because I didn't set the vector field in queryRequest:

```ts
node:internal/process/esm_loader:97
    internalBinding('errors').triggerUncaughtException(
                              ^

[PineconeError: PineconeClient: Error calling query: TypeError: stream.getReader is not a function]
```

### Expected Behavior

Query all vector without specific vectors field.

### Steps To Reproduce

Invoke query function.

### Environment

```markdown
- **OS**:
- **Language version**:
- **Pinecone client version**:
```

**Comment by Penggeor** [comment]
By the way, the thrown error is entirely irrelevant to its real error source. Unfriendly feedback is an obstacle for developers to inspect their code.

**Comment by jhamon** [comment]
The type has labeled `values` as optional because you must pass _either_ `values` or `id` of a record in your index with vector values to use as the query. In order to make a query you must either pass a `values` array or the `id` of a record stored in your index you want to use for the query. One way or another, the backend needs to know what vector values you want to query with because it can't tell you the `topK` most _similar_ results without something to compare to.

> By the way, the thrown error is entirely irrelevant to its real error source. Unfriendly feedback is an obstacle for developers to inspect their code.

I completely agree with this.

We think we have made some significant improvements in the UX (especially around errors) of this in the updated client that got released last week. There are now runtime validations to give improved error messages. Check out the [release notes](https://github.com/pinecone-io/pinecone-ts-client/releases) and [v1 migration guide](https://github.com/pinecone-io/pinecone-ts-client/blob/main/v1-migration.md) to start using the new client.
