### ISSUE TITLE
[Bug] Failed getting project name. API key is missing or invalid for the environment.

### ISSUE THREAD

**Issue by saikarthikp9** [pinecone-io/pinecone-ts-client#72]
### Is this a new bug?

- [X] I believe this is a new bug
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

When trying to init the PineconeClient, get the following error:

PineconeError: Failed getting project name. Error: Unauthorized - API key is missing or invalid for the environment "asia-southeast1-gcp-free". Check that the correct environment is specified.

I have verified the API key and the environment. I have tested the same with v0.1.6, v0.1.5, v0.1.4.

### Expected Behavior

It should return the client instance after authorization.

### Steps To Reproduce

import { PineconeClient } from '@pinecone-database/pinecone';

// Create a client
const pineconeClient = new PineconeClient();
```
async function initialize() {
  try {
      // Initialize the client
      await pineconeClient.init({
          apiKey: "REPLACE_THIS_APIKEY",
          environment: "REPLACE_THIS_ENV",
      });
  } catch(err) {
      console.log(err)
  }
}
```

### Relevant log output

```shell
[PineconeError: Failed getting project name. TypeError: fetch failed]
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[PineconeError: Failed getting project name. Error: Unauthorized - API key is missing or invalid for the environment "asia-southeast1-gcp-free". Check that the correct environment is specified.]
```

### Environment

```markdown
- **OS**: MacOS Monterey 12.6.3
- **Language version**: Node.js v20.3.1
- **Pinecone client version**: v0.1.6
```

### Additional Context
Followed this guide:
https://docs.pinecone.io/docs/quickstart
Same thing works using the Python client.

**Comment by saikarthikp9** [comment]
I tried hardcoding the project name in the source code of this package then when I try to describe an index using describeIndex(), I see a similar error: 
[PineconeError: PineconeClient: Error calling describeIndex: API key is missing or invalid for the environment "asia-southeast1-gcp-free". Check that the correct environment is specified.]

I am sure the API key is correct, since I used the same key to test in Python.

**Comment by MejanH** [comment]
I am also facing this issue, also checked if secrets are loading or not. but no luck.

**Comment by vladaCizek** [comment]
I'm experiencing the same issue on windows 11.

**Comment by jhamon** [comment]
I can't see anything wrong from the code that you shared. I see that you're targeting one of our free environments which have some limitations and can be archived after a period of inactivity. Perhaps that could explain the issue?

You've probably figured this out or moved on by now because this issue is quite old, but I want to mention for anyone else that finds this thread that we've recently been putting in a lot of work to improve the pinecone typescript client so you might be interested in checking out the v1 release (specifically `1.0.1`). Here are the [release notes](https://github.com/pinecone-io/pinecone-ts-client/releases) and the [v1 migration guide](https://github.com/pinecone-io/pinecone-ts-client/blob/main/v1-migration.md) to get started using the new client. 

If you run into a similar issue with the updated client, please open a new issue and I'll help you get to the bottom of it.
